/**
 * State Actions
 */

// Search Engine Filters
export const CHANGE_DISH       = "SEARCH_FILTER/CHANGE_DISH_TYPE";
export const CHANGE_MEAL       = "SEARCH_FILTER/CHANGE_MEAL_TYPE";
export const CHANGE_PRODUCT    = "SEARCH_FILTER/CHANGE_PRODUCT_TYPE";
export const CHANGE_CULINARY   = "SEARCH_FILTER/SELECT_CULINARY_TYPE";
export const CHANGE_DIFFICULTY = "SEARCH_FILTER/SELECT_DIFFICULTY_TYPE";